# Generated by Django 2.2 on 2019-04-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ques_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplechoice.Track')),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=250)),
                ('votes', models.IntegerField()),
                ('ans', models.BooleanField(default=False)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplechoice.Question')),
            ],
        ),
    ]
